apiVersion: v1
kind: Service
metadata:
    name: "welyaks2-7944"
    labels:
        app: "welyaks2-7944"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "welyaks2-7944"